---
- name: Setup Jenkins users and groups
  include_tasks: user.yaml

- name: Create project directory
  file:
    path: "{{ jenkins_docker_path }}"
    state: directory
    mode: '0755'
    owner: 1004
    group: 1004

- name: Render docker-compose configuration
  template:
    src: docker-compose.yaml.j2
    dest: "{{ jenkins_docker_path }}/docker-compose.yaml"
    mode: '0644'

- name: Render docker configuration
  template:
    src: Dockerfile.j2
    dest: "{{ jenkins_docker_path }}/Dockerfile"
    mode: '0644'

- name: Render docker configuration
  template:
    src: plugins.j2
    dest: "{{ jenkins_docker_path }}/plugins.txt"
    mode: '0644'

- name: Start Jenkins using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ jenkins_docker_path }}"
    state: present
    build: always
    wait: true
    wait_timeout: 360