FROM jenkins/jenkins:2.546

USER root
RUN groupmod -g 1004 jenkins && \
    usermod -u 1004 -g 1004 jenkins

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

USER jenkins