FROM jenkins/jenkins:2.546

USER root
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN apt-get update && apt-get install -y lsb-release && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && apt-get install -y docker-ce-cli && \
    groupmod -g 1004 jenkins && \
    usermod -u 1004 -g 1004 jenkins && \
    groupadd -g 977 docker && usermod -aG docker jenkins && \
    jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

USER jenkins