all:
  children:
    prometheus:
      hosts:
        dev:
          ansible_host: 10.0.1.139
        dev2:
          ansible_host: 10.0.1.140
    grafana:
      hosts:      
        dev3:
          ansible_host: 10.0.1.139
        dev4:
          ansible_host: 10.0.1.140