---
- name: Create project directory
  file:
    path: "{{ jenkins_project_path }}"
    state: directory
    mode: '0755'
    owner: 1004
    group: 1004

- name: Render JCasC configuration from template
  template:
    src: casc.yaml.j2
    dest: "{{ jenkins_project_path }}/casc.yaml"
    owner: 1004
    group: 1004
    mode: '0644'

# - name: Start Jenkins and build custom image
#   community.docker.docker_compose_v2:
#     project_src: "{{ docker_files_path }}"
#     state: present
#     build: always  # To wymusi zbudowanie obrazu z Twojego Dockerfile